"""Add is_verified column to User

Revision ID: 418dc6679f8d
Revises: 5e9ce79dca06
Create Date: 2025-04-30 14:48:45.773286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418dc6679f8d'
down_revision = '5e9ce79dca06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
